import NewProductForm from '@/components/products/NewProductForm'
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function NewProductPage() {
  const router = useRouter();

  const addProductHandler = async (enteredProductData) => {
    const res = await axios.post("/api/products", enteredProductData, {
      headers: { "Content-Type": "application/json" },
    });

    router.push("/");
  };

  return (
    <>
      <Head>
        <title>Add new product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewProductForm onAddProduct={addProductHandler} />
    </>
  )
}
