import ProductDetails from '@/components/products/ProductDetails'
import Product from '@/models/Product';
import { dbConnect } from '@/util/mongo';
import mongoose from 'mongoose';
import Head from 'next/head';
import React from 'react'

export default function ProductDetailsPage(props) {
  return (
    <>
      <Head>
        <title>{props.productData.name} details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetails
        image= {props.productData.image}
        name= {props.productData.name}
        price= {props.productData.price}
        desc= {props.productData.desc}
      />
    </>
  )
}

export async function getStaticPaths() {
  // connect to DB to get product ids
  dbConnect();
  const products = await Product.find({}, { _id: 1 });

  return {
    fallback: false,  // if false -> only accept provided ids otherwise show error page
    paths: products.map((product) => (
      {
        params: { productId: product._id.toString()},
      }
    ))
  }
}

export async function getStaticProps(context) {
  const productId = context.params.productId;
  // select product from DB
  const selectedProduct = await Product.findById({
    _id: new mongoose.Types.ObjectId(productId)
  })

  return {
    props: {
      productData: {
        image: selectedProduct.image,
        name: selectedProduct.name,
        price: selectedProduct.price,
        desc: selectedProduct.desc,
        id: productId,
      }
    }
  }
}