import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ProductList from '@/components/products/ProductList'
import axios from 'axios'
import { dbConnect } from '@/util/mongo'
import Product from '@/models/Product'

const inter = Inter({ subsets: ['latin'] })

export default function HomePage(props) {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductList products={props.products} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  // fetch data from an API or DB
  dbConnect();
  const productsData = await Product.find();

  return {
    props: {
      products: productsData.map((product) => ({
        id: product._id.toString(),
        name: product.name,
        image: product.image,
        price: product.price,
      }))
    }
  }
}

// You can fetch data from API endpoint or as you now at server side you can fetch DB directly


// export async function getServerSideProps() {
//   // fetch data from an API or DB
//   // const res = await axios.get(`${process.env.APP_DEV || process.env.APP_PROD}/api/products`);
//   // You can fetch data from API endpoint or as you now at server side you can fetch DB directly
//   dbConnect();
//   const productsData = await Product.find();
//   return {
//     props: {
//       products: res.data.data.map((product) => ({
//         id: product._id.toString(),
//         name: product.name,
//         image: product.image,
//         price: product.price,
//       }))
//     }
//   }
// }

// export async function getStaticProps() {
//   // fetch data from an API or DB
//   const res = await axios.get("http://localhost:3000/api/products");
//   return {
//     props: {
//       products: res.data.data.map((product) => ({
//         id: product._id.toString(),
//         name: product.name,
//         image: product.image,
//         price: product.price,
//       }))
//     },
//     revalidate: 1,
//   }
// }

// ag32yzNCuvwksNdPlzXRklH7